import { execFileSync } from "child_process";
import * as crypto from "crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "fs";
import { stat } from "fs/promises";
import { builtinModules, createRequire } from "module";
import { dirname, isAbsolute, posix, resolve } from "path";
import { decode, encode } from "vlq";
import { normalPath } from "./misc";

const SDK_PATH = normalPath(resolve(__dirname, "..", ".."));

// TODO: refactor Bundle into a dedicated class with methods to check if the bundling is
// finished, invalidated, etc.

export interface Bundle {
  directory: string;
  hash: string;
  outfilePath: string;
  sourcemapPath: string;
  /**
   * A list of files that were used to create the bundle (directly or indirectly).
   * If none of the listed files have been modified since the last bundle, it's *probably* safe to reuse the bundle.
   *
   * Note: this isn't fully reliable since there can be edge cases where none of the files have been modified
   * but a different bundle would be generated by esbuild. See https://github.com/evanw/esbuild/issues/673
   */
  inputFiles: string[];
  time: Date;
}

/**
 * Preamble that gives Wing-generated CJS entrypoints local `module`/`exports`
 * bindings so they keep working when bundled as ESM.
 */
export const CJS_EXPORTS_SHIM =
  "const module = { exports: {} };\n" + "const exports = module.exports;\n";

/**
 * How to re-export CJS-style `exports` / `module.exports` for cloud runtimes
 * after an ESM bundle.
 *
 * - `"handler"` — named `export const handler` (AWS Lambda `index.handler`)
 * - `"default"` — `export default` (Azure Functions classic / function.json)
 * - `"none"` — shim only (GCP side-effect registration via functions-framework,
 *   or callers that append their own footer)
 */
export type EsmCloudExportStyle = "handler" | "default" | "none";

export interface PrepareEsmEntrypointOptions {
  /**
   * @default "none"
   */
  readonly exportStyle?: EsmCloudExportStyle;
}

/**
 * Wraps a Wing-generated CJS entrypoint so it can be bundled with
 * `createBundle(...)` (ESM) while still exposing the entry the
 * cloud runtime expects.
 *
 * Writes a sibling `*.esm.*` file next to `entrypoint` and returns its path.
 */
export function prepareEsmEntrypoint(
  entrypoint: string,
  options: PrepareEsmEntrypointOptions = {},
): string {
  const exportStyle: EsmCloudExportStyle = options.exportStyle ?? "none";
  const contents = readFileSync(entrypoint, "utf-8");

  let footer = "";
  if (exportStyle === "handler") {
    // Look up at call time so lazy assignment to exports.handler still works.
    footer =
      "\nexport const handler = (...args) => module.exports.handler(...args);\n";
  } else if (exportStyle === "default") {
    // Azure classic model: CJS uses `module.exports = async function...`.
    // ESM import() yields `{ default }`; LegacyFunctionLoader picks the sole key.
    footer =
      "\nexport default function (...args) {\n" +
      "  const fn =\n" +
      '    typeof module.exports === "function"\n' +
      "      ? module.exports\n" +
      "      : (module.exports.default ?? module.exports.handler);\n" +
      "  return fn.apply(this, args);\n" +
      "}\n";
  }

  const wrapped = CJS_EXPORTS_SHIM + contents + footer;

  const wrappedPath = entrypoint.replace(/(\.[cm]?js)$/, ".esm$1");
  const outPath =
    wrappedPath === entrypoint ? `${entrypoint}.esm.js` : wrappedPath;
  writeFileSync(outPath, wrapped);
  return outPath;
}

export interface CreateBundleOptions {
  /**
   * Leave npm packages imported by user code (e.g. externs) out of the bundle
   * and load them natively at runtime, as long as Node would resolve the exact
   * same package from the bundle's output directory.
   *
   * This is meant for targets that run the bundle in place on the developer's
   * machine (the simulator), where the project's `node_modules` is available.
   * It lets inflight code use packages that cannot be bundled (native addons,
   * optional dependencies that aren't installed, code that relies on
   * `__dirname`, etc.). Cloud targets must not use this, since the bundle is
   * shipped without `node_modules`.
   *
   * Can be disabled with `WING_SIM_BUNDLE_ALL_PACKAGES=1`.
   *
   * @default false
   */
  readonly externalizeInstalledPackages?: boolean;
}

/**
 * Bundles a javascript entrypoint into a single file.
 * @param entrypoint The javascript entrypoint
 * @param outputDir Defaults to `${entrypoint}.bundle`
 * @param external external packages
 * @param options additional bundling options
 * @returns Bundle information
 */
export function createBundle(
  entrypoint: string,
  external: string[] = [],
  outputDir?: string,
  options: CreateBundleOptions = {},
): Bundle {
  const normalEntrypoint = normalPath(realpathSync(entrypoint));
  const outdir = outputDir
    ? normalPath(realpathSync(outputDir))
    : `${normalEntrypoint}.bundle`;
  mkdirSync(outdir, { recursive: true });

  // Always emit ESM (.mjs) so Node treats the file as an ES module when
  // forked (e.g. by the simulator Sandbox) and top-level await works.
  const outfileName = "index.mjs";
  const soucemapFilename = `${outfileName}.map`;

  const outfile = posix.join(outdir, outfileName);
  const outfileMap = posix.join(outdir, soucemapFilename);

  const stats = statSync(normalEntrypoint);

  // Track what time we started bundling so we can invalidate the bundle if any
  // of the source files are modified after this time.
  let startTime = new Date();

  // For unknown reasons, the date created here by JavaScript can sometimes be a
  // few milliseconds before the last modification date of the entrypoint file.
  // This can cause the bundle to be invalidated when it shouldn't be. To
  // prevent this flakiness in unit tests, we check if the modification date of the
  // entrypoint file and update the start time if it's newer.
  if (stats.mtime > startTime) {
    startTime = stats.mtime;
  }

  // eslint-disable-next-line import/no-extraneous-dependencies,@typescript-eslint/no-require-imports
  const esbuilder: typeof import("esbuild") = require("esbuild");

  const nodePaths = process.env.WING_NODE_MODULES
    ? [normalPath(process.env.WING_NODE_MODULES as string)]
    : undefined;

  const allExternal = [...external];
  if (
    options.externalizeInstalledPackages &&
    !process.env.WING_SIM_BUNDLE_ALL_PACKAGES
  ) {
    allExternal.push(
      ...findRuntimeResolvablePackages(esbuilder, normalEntrypoint, outdir, {
        nodePaths,
      }),
    );
  }

  let esbuild = esbuilder.buildSync({
    bundle: true,
    entryPoints: [normalEntrypoint],
    outfile,
    // otherwise there are problems with running azure cloud functions:
    // https://stackoverflow.com/questions/70332883/webpack-azure-storage-blob-node-fetch-abortsignal-issue
    keepNames: true,
    // if the user has specified a node_modules directory to resolve from
    nodePaths,
    alias: {
      "@winglang/sdk": SDK_PATH,
    },
    minify: false,
    sourcemap: "linked",
    platform: "node",
    target: "node20",
    format: "esm",
    external: allExternal,
    // Define a real Node `require` before esbuild's __require shim so leftover
    // dynamic requires (e.g. require("node:assert") inside bundled CJS) work
    // instead of throwing.
    banner: {
      js: 'import { createRequire } from "node:module";const require = createRequire(import.meta.url);',
    },
    metafile: true,
    write: false,
  });

  if (esbuild.errors.length > 0) {
    const errors = esbuild.errors.map((e) => e.text).join("\n");
    throw new Error(`Failed to bundle function: ${errors}`);
  }

  const bundleOutput = esbuild.outputFiles[1];

  // ensure source paths have posix path separators
  const sourcemapData = JSON.parse(
    new TextDecoder().decode(esbuild.outputFiles[0].contents),
  );
  fixSourcemaps(sourcemapData);

  writeFileSync(outfile, bundleOutput.contents);
  writeFileSync(outfileMap, JSON.stringify(sourcemapData));

  // calculate a md5 hash of the contents of asset.path
  const codeHash = crypto
    .createHash("md5")
    .update(bundleOutput.contents)
    .digest("hex");

  const outKeys = Object.keys(esbuild.metafile?.outputs ?? {});
  const outKey = outKeys.find((k) => k.endsWith(outfileName));
  if (!outKey) {
    throw new Error(`Couldn't find metadata for ${outfileName} from esbuild.`);
  }

  const inputFiles = Object.keys(esbuild.metafile?.outputs[outKey].inputs);

  return {
    directory: outdir,
    hash: codeHash,
    outfilePath: outfile,
    sourcemapPath: outfileMap,
    inputFiles,
    time: startTime,
  };
}

const BUILTIN_MODULES = new Set(builtinModules);

/**
 * Returns the npm package name of a bare import specifier (e.g. `vite`,
 * `@aws-sdk/client-s3` for `@aws-sdk/client-s3/dist/foo.js`), or `undefined` if
 * the specifier is not a bare package specifier (relative/absolute paths,
 * `node:` builtins, subpath imports, URLs, etc.).
 */
export function packageNameOf(specifier: string): string | undefined {
  if (
    specifier.startsWith(".") ||
    specifier.startsWith("#") ||
    isAbsolute(specifier) ||
    /^[a-zA-Z][a-zA-Z\d+\-.]*:/.test(specifier) // node:, file:, data:, C:\, ...
  ) {
    return undefined;
  }
  const parts = specifier.split("/");
  const name = specifier.startsWith("@")
    ? parts.length >= 2 && parts[1]
      ? `${parts[0]}/${parts[1]}`
      : undefined
    : parts[0];
  if (!name || BUILTIN_MODULES.has(name)) {
    return undefined;
  }
  return name;
}

/**
 * Finds the directory of package `name` the way Node's resolver does for bare
 * specifiers: walk up from `fromDir` looking for `node_modules/<name>`, then
 * fall back to `extraPaths`. Returns the real path, or `undefined`.
 */
function findPackageDir(
  name: string,
  fromDir: string,
  extraPaths: string[] = [],
): string | undefined {
  const candidates: string[] = [];
  let dir = resolve(fromDir);
  while (true) {
    if (posix.basename(normalPath(dir)) !== "node_modules") {
      candidates.push(resolve(dir, "node_modules", name));
    }
    const parent = dirname(dir);
    if (parent === dir) {
      break;
    }
    dir = parent;
  }
  candidates.push(...extraPaths.map((p) => resolve(p, name)));

  for (const candidate of candidates) {
    if (existsSync(resolve(candidate, "package.json"))) {
      return normalPath(realpathSync(candidate));
    }
  }
  return undefined;
}

/**
 * Whether Node (and esbuild) treat `file` as an ES module, i.e. whether
 * esbuild applies Node's (rather than Babel's) interop rules to its imports.
 */
function isNodeEsmFile(file: string): boolean {
  if (/\.m[jt]s$/.test(file)) {
    return true;
  }
  if (/\.c[jt]s$/.test(file)) {
    return false;
  }
  let dir = dirname(file);
  while (true) {
    const pkgJson = resolve(dir, "package.json");
    if (existsSync(pkgJson)) {
      try {
        return JSON.parse(readFileSync(pkgJson, "utf-8")).type === "module";
      } catch {
        return false;
      }
    }
    const parent = dirname(dir);
    if (parent === dir) {
      return false;
    }
    dir = parent;
  }
}

/**
 * Checks whether an ESM `import` of `specifier` (from a file in `resolveDir`
 * that esbuild treats with Babel-style interop, e.g. a `.ts` extern) behaves
 * the same whether the package is bundled or loaded natively by Node.
 *
 * That is the case when the target is an ES module, or a CommonJS module that
 * doesn't use the `__esModule` marker (for which esbuild would pick
 * `exports.default` as the default import, while Node picks `module.exports`).
 */
function isImportInteropSafe(
  esbuilder: typeof import("esbuild"),
  specifier: string,
  resolveDir: string,
  nodePaths: string[] | undefined,
): boolean {
  let inputs: Record<string, { format?: string }>;
  try {
    // Resolve the specifier with esbuild's resolver (same conditions as the
    // real build) without descending into its dependencies.
    const r = esbuilder.buildSync({
      entryPoints: [specifier],
      absWorkingDir: resolveDir,
      nodePaths,
      bundle: false,
      write: false,
      metafile: true,
      platform: "node",
      target: "node20",
      format: "esm",
      outdir: resolveDir,
      logLevel: "silent",
    });
    inputs = r.metafile.inputs;
  } catch {
    return false;
  }
  const entries = Object.entries(inputs);
  if (entries.length !== 1) {
    return false;
  }
  const [file, { format }] = entries[0];
  if (format === "esm") {
    return true;
  }
  if (format !== "cjs") {
    // e.g. JSON files, which Node can't `import` without import attributes
    return false;
  }
  try {
    const code = readFileSync(resolve(resolveDir, file), "utf-8");
    return !code.includes("__esModule");
  } catch {
    return false;
  }
}

/**
 * Checks whether a `require()` of `specifier` from `importer` resolves (with
 * Node's own resolver and `require` conditions) to a CommonJS file, so that
 * calling Node's native `require` for it works the same as bundling it.
 * `require()`-ing an ES module isn't supported by every Node.js 20 release.
 */
function isRequireSafe(specifier: string, importer: string): boolean {
  let resolved: string;
  try {
    resolved = createRequire(importer).resolve(specifier);
  } catch {
    return false;
  }
  if (!isAbsolute(resolved)) {
    return false;
  }
  return !isNodeEsmFile(resolved);
}

/**
 * Returns the packages imported (directly) by non-SDK code in the bundle that
 * can be safely left out of the bundle and loaded natively at runtime.
 *
 * A package qualifies if:
 * - Node, starting from `outdir` (where the bundle is written and executed),
 *   resolves the exact same package directory that esbuild would have bundled
 *   for every importer (so packages that only resolve through `nodePaths`, or
 *   that the SDK depends on with a different copy, stay bundled), and
 * - loading it natively doesn't change import semantics (see
 *   `isImportInteropSafe`).
 */
export function findRuntimeResolvablePackages(
  esbuilder: typeof import("esbuild"),
  entrypoint: string,
  outdir: string,
  options: { nodePaths?: string[] } = {},
): string[] {
  // A cheap pre-pass: don't descend into any package, only record which
  // packages are imported and by whom.
  let result: import("esbuild").BuildResult<{ metafile: true; write: false }>;
  try {
    result = esbuilder.buildSync({
      bundle: true,
      entryPoints: [entrypoint],
      outdir,
      nodePaths: options.nodePaths,
      alias: {
        "@winglang/sdk": SDK_PATH,
      },
      platform: "node",
      target: "node20",
      format: "esm",
      packages: "external",
      metafile: true,
      write: false,
      logLevel: "silent",
    });
  } catch {
    // Let the real build report the error.
    return [];
  }

  const cwd = process.cwd();
  // package name -> directories esbuild would bundle it from
  const bundleDirs = new Map<string, Set<string | undefined>>();
  const userPackages = new Set<string>();
  const unsafe = new Set<string>();

  for (const [inputPath, input] of Object.entries(result.metafile.inputs)) {
    const importer = normalPath(resolve(cwd, inputPath));
    const importerDir = dirname(importer);
    const isSdk = importer.startsWith(SDK_PATH + "/");
    for (const imp of input.imports) {
      if (!imp.external) {
        continue;
      }
      const name = packageNameOf(imp.path);
      // The SDK is always bundled from its aliased location.
      if (!name || name === "@winglang/sdk") {
        continue;
      }

      const dirs = bundleDirs.get(name) ?? new Set();
      dirs.add(findPackageDir(name, importerDir, options.nodePaths));
      bundleDirs.set(name, dirs);

      if (isSdk || unsafe.has(name)) {
        continue;
      }
      userPackages.add(name);

      // Externalized `require()` calls go to Node's real `require` (see the
      // banner in `createBundle`); externalized imports are left as ESM
      // imports. Make sure neither changes what the importer gets.
      let safe: boolean;
      if (imp.kind === "import-statement" || imp.kind === "dynamic-import") {
        safe =
          isNodeEsmFile(importer) ||
          isImportInteropSafe(
            esbuilder,
            imp.path,
            importerDir,
            options.nodePaths,
          );
      } else if (imp.kind === "require-call") {
        safe = isRequireSafe(imp.path, importer);
      } else {
        safe = false;
      }
      if (!safe) {
        unsafe.add(name);
      }
    }
  }

  const packages = new Array<string>();
  for (const name of userPackages) {
    if (unsafe.has(name)) {
      continue;
    }
    const runtimeDir = findPackageDir(name, outdir);
    const dirs = bundleDirs.get(name)!;
    if (runtimeDir !== undefined && dirs.size === 1 && dirs.has(runtimeDir)) {
      packages.push(name, `${name}/*`);
    }
  }
  return packages;
}

/**
 * Archives (zips) the contents of `srcDir` into a single zip file at `destFile`.
 *
 * This replaces cdktf's `TerraformAsset` with `AssetType.ARCHIVE`, whose internal
 * implementation shells out to `node .../private/fs.js <src> <dest>` using a
 * command string that does NOT quote the paths. When the project directory (or
 * any path component) contains spaces, the shell splits on the spaces and the
 * archive is written to the wrong location (or fails entirely), which later
 * causes errors like `opening S3 object source (assets/.../archive.zip): no
 * such file or directory` during `terraform apply`.
 *
 * Instead of relying on that shell string, we invoke the archiver directly with
 * `execFileSync` and an array of arguments (no shell), so paths containing
 * spaces are handled correctly. The resulting zip file is then presented to
 * `TerraformAsset` as a single `AssetType.FILE`, which is simply copied into the
 * output directory with `copyFileSync` (no shell involved).
 */
export function createArchive(srcDir: string, destFile: string): void {
  // Reuse the archiver bundled with cdktf (this repo pins cdktf to an exact
  // version, so this internal module path is stable). It is invoked as a CLI
  // with array arguments rather than a shell string to preserve spaces.
  // eslint-disable-next-line import/no-extraneous-dependencies, @typescript-eslint/no-require-imports
  const archiveScript = require.resolve("cdktf/lib/private/fs") as string;
  execFileSync(process.execPath, [archiveScript, srcDir, destFile]);
}

export interface SourceMap {
  sourceRoot?: string;
  sources: string[];
  sourcesContent: string[];
  mappings: string;
}

/**
 * Takes a bundled sourcemap and does the following fixes:
 * - Normalizes paths in sources and sourceRoot
 * - Removes duplicate sources and sourcesContent
 * - Updates mappings to reflect the new source indices
 *
 * The duplicate sources come from esbuild's strange handling of multiple files being bundled that point to the same source (e.g. inflights that point to one .w file)
 * See https://github.com/evanw/esbuild/issues/933
 */
export function fixSourcemaps(sourcemapData: SourceMap): void {
  // normalize sourceRoot
  if (sourcemapData.sourceRoot) {
    sourcemapData.sourceRoot = normalPath(sourcemapData.sourceRoot);
  }

  // normalize sources and remove duplicates
  const sourceSet: string[] = [];
  const newSourceContents: string[] = [];
  const sourceIndexMap: Record<number, number> = {};
  let hasSourceDupes = false;
  sourcemapData.sources.forEach((source, idx) => {
    const newPath = normalPath(source);
    sourcemapData.sources[idx] = newPath;

    const existingIndex = sourceSet.indexOf(newPath);
    if (existingIndex === -1) {
      sourceSet.push(newPath);
      newSourceContents.push(sourcemapData.sourcesContent[idx]);
      sourceIndexMap[idx] = sourceSet.length - 1;
    } else {
      hasSourceDupes = true;
      sourceIndexMap[idx] = existingIndex;
    }
  });

  sourcemapData.sources = sourceSet;
  sourcemapData.sourcesContent = newSourceContents;

  // fast path: No source duplicates so no need to update mappings
  if (!hasSourceDupes) {
    return;
  }

  // update mappings
  let newMapping = "";
  let characterIndex = 0;
  let lastFile = 0;
  let lastTrueFile = 0;
  while (characterIndex < sourcemapData.mappings.length) {
    const char = sourcemapData.mappings[characterIndex];
    // `;` and `,` are separators between the segments of interest
    if (char === ";" || char === ",") {
      newMapping += char;
      characterIndex++;
      continue;
    }

    // get next slice of segment data
    let segment = "";
    let nextChar = char;
    while (nextChar !== undefined && nextChar !== "," && nextChar !== ";") {
      segment += nextChar;
      nextChar = sourcemapData.mappings[++characterIndex];
    }
    const decoded = decode(segment);
    if (decoded.length === 1) {
      newMapping += segment;
      continue;
    }

    const sourceRelative = decoded[1];
    const originalSource = lastTrueFile + sourceRelative;
    const newSourceIndex = sourceIndexMap[originalSource];
    lastTrueFile = originalSource;

    const newRelativeValue = newSourceIndex - lastFile;
    lastFile = newSourceIndex;

    if (newRelativeValue === decoded[1]) {
      // no change was made, avoid re-encoding
      newMapping += segment;
    } else {
      decoded[1] = newRelativeValue;
      newMapping += encode(decoded);
    }
  }

  sourcemapData.mappings = newMapping;
}

export async function filesModifiedSince(
  filePaths: string[],
  directory: string,
  dateTime: Date,
): Promise<string[]> {
  const absolutePaths = filePaths.map((filePath) =>
    resolve(directory, filePath),
  );

  try {
    const statsPromises = absolutePaths.map((filePath) => stat(filePath));
    const stats = await Promise.all(statsPromises);
    const changedFiles = new Array<string>();

    for (let i = 0; i < absolutePaths.length; i++) {
      if (stats[i].mtime > dateTime) {
        console.error(
          `File ${absolutePaths[i]} has been modified since the last bundle`,
          stats[i].mtime,
          dateTime,
        );
        changedFiles.push(absolutePaths[i]);
      }
    }

    return changedFiles;
  } catch (error) {
    console.error("Error checking file modification times:", error);
    throw error;
  }
}

export async function isBundleInvalidated(
  entrypoint: string,
  bundle: Bundle,
  log?: (msg: string) => void,
): Promise<boolean> {
  const modifiedFiles = await filesModifiedSince(
    [entrypoint, ...bundle.inputFiles],
    process.cwd(),
    bundle.time,
  );
  if (modifiedFiles.length === 0) {
    return false;
  }

  if (process.env.DEBUG) {
    log?.(
      `Files modified since last bundling: [${modifiedFiles
        .map((x) => `"${x}"`)
        .join(", ")}]`,
    );
  }

  return true;
}
