# See https://doc.mergify.io
queue_rules:
  - name: default
    conditions:
      - status-success=Validate PR title
      - or:
        - status-success=Quality Gate
        - -files~=^(?!docs/|logo/)

pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from {{ base }} and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(🚧 pr/do-not-merge|⚠️ pr/review-mutation)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - -approved-reviews-by~=author
      - check-success=Validate PR title
      - base=main
      - or:
        - check-success=Quality Gate
        - -files~=^(?!docs/|logo/)

  - name: requires manual merge
    conditions:
      - files=.mergify.yml
      - -title~=(?i)wip
      - -label~=(🚧 pr/do-not-merge|⚠️ pr/review-mutation|⚠️ mergify/review-config)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - -approved-reviews-by~=author
      - check-success=Validate PR title
      - check-success=Quality Gate
      - base=main
    actions:
      comment:
        message: Thank you for contributing! Your pull request contains mergify configuration changes and needs manual merge from a maintainer (be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      label:
        add:
          - ⚠️ mergify/review-config
      request_reviews:
        teams:
          - "@winglang/maintainers"
