packages:
  - "apps/*"
  - "libs/*"
  - "tools/*"
  - "wing-console/packages/*"
  - "wing-console/console/*"
  - "wing-console/tools/*"
  - "examples/tests/*"
  - "apps/jsii-docgen/test/__fixtures__/**"