packages:
  - "packages/*"
  - "packages/@wingcloud/*"
  - "packages/@winglang/*"
  - "packages/@winglibs/*"
  - "tools/*"
  - "docs"
  - "docs/docs"
  - "wing-console/packages/*"
  - "wing-console/console/*"
  - "wing-console/tools/*"
  - "tests/*"
  - "packages/@winglang/jsii-docgen/test/__fixtures__/**"
