packages:
  - "apps/*"
  - "libs/*"
  - "tools/*"
  - "docs/docs"
  - "apps/wing-console/packages/*"
  - "apps/wing-console/console/*"
  - "apps/wing-console/tools/*"
  - "examples/tests/*"
  - "examples/*"
  - "scripts/compatibility-matrix-automation"
  - "apps/jsii-docgen/test/__fixtures__/**"
