[package]
name = "wingii"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
blake3 = "1.5"
speedy = "0.8"
camino = "1.1"

[dev-dependencies]
rand = "0.8"
filetime = "0.2"
