import { Project, TextFile } from "projen";

export interface EditorconfigFileOptions {
  /**
   * @default 2
   */
  readonly indentSize?: number;
}

export class EditorconfigFile extends TextFile {
  constructor(project: Project, options?: EditorconfigFileOptions) {
    super(project, ".editorconfig");

    project.addPackageIgnore("/.editorconfig");

    this.addLine(
      `# ~~ Generated by projen. To modify, edit .projenrc.js and run \"npx projen\".`,
    );
    this.addLine("root = true");
    this.addLine("");

    this.addLine("[*]");
    this.addLine("indent_style = space");
    this.addLine(`indent_size = ${options?.indentSize ?? 2}`);
    this.addLine("end_of_line = lf");
    this.addLine("charset = utf-8");
    this.addLine("trim_trailing_whitespace = true");
    this.addLine("insert_final_newline = true");
    this.addLine("");

    this.addLine("[*.md]");
    this.addLine("trim_trailing_whitespace = false");
    this.addLine("");
  }
}
