name: Bug Report 🐞
description: Create a bug report
labels: ["🐛 bug"]
body:
- type: markdown
  attributes:
    value: |
       :pray: Thanks for taking the time to fill out this bug report! Feel free to ping us on [Wing Slack](https://t.winglang.io/slack) if you have any questions or need help.
- type: markdown
  attributes:
    value: |
       ## Bug Report
- type: textarea
  id: i-tried-this
  attributes:
    label: "I tried this:"
    placeholder: "What did you try to do? A code snippet or exact command line is ideal."
  validations:
    required: true
- type: textarea
  id: instead-what-happened
  attributes:
    label: "This happened:"
    placeholder: "What happend instead of what you've expected?"
  validations:
    required: true
- type: textarea
  id: what-did-you-expect
  attributes:
    label: "I expected this:"
    placeholder: "What did you expect to happen? Describe the output or behavior you expected to see."
  validations:
    required: true    
- type: textarea
  id: workaround
  attributes:
    label: "Is there a workaround?"
    placeholder: "What's the workaround to avoid this issue?"
- type: dropdown
  id: Component
  attributes:
    label: "Component"
    description: "Which component(s) in the toolchain is this related to?"
    multiple: true
    options:
    - Language Design
    - Compiler
    - SDK
    - Wing Console
    - Playground
    - Tutorial
    - IDE Extension
    - CLI
    - Plugins
    - Documentation
    - Development Environment
    - Contributor Experience
    - Other
  validations:
    required: true

- type: markdown
  attributes:
    value: |
       ## Environment

- type: input
  id: wing-version
  attributes:
    label: "Wing Version"
    placeholder: "wing --version"

- type: input
  id: console-version
  attributes:
    label: "Wing Console Version"
    placeholder: "Wing Console > About Wing Console (if relevant)"

- type: input
  id: node
  attributes:
    label: "Node.js Version"
    placeholder: "node --version"

- type: dropdown
  id: platform
  attributes:
    label: "Platform(s)"
    multiple: true
    options:
      - MacOS
      - Linux
      - Windows
      - Other

- type: markdown
  attributes:
    value: |
       ## Misc

- type: textarea
  attributes:
    label: Anything else?
    placeholder: |
      Links? References? Logs? Anything that will give us more context about the issue you are encountering.
      Tip: You can attach images or log files by dragging files in.
  validations:
    required: false

- type: textarea
  attributes:
    label: Community Notes
    value: |
      <!-- Please keep this note for the community -->
      * Please vote by adding a 👍 reaction to the issue to help us prioritize.
      * If you are interested to work on this issue, please leave a comment.
