blank_issues_enabled: true
contact_links:
  - name: Community Slack
    url: https://join.slack.com/t/winglang/shared_invite/zt-1i7jb3pt3-lb0RKOSoLA1~pl6cBnP2tA
    about: Come hang out, ask questions, help friends!
