name: Enhancement 🚀
description: Suggest a new feature or other improvement
labels: ["✨ enhancement","needs-discussion"]
body:
- type: markdown
  attributes:
    value: |
       :pray: Thanks for taking the time to fill out this enhancement request! Feel free to ping us on [Wing Slack](https://t.winglang.io/slack) if you have any questions or need help.
- type: markdown
  attributes:
    value: |
      ## Enhancement Request
- type: textarea
  id: spec
  attributes:
    label: Feature Spec
    description:
    placeholder: |
      Describe the feature as if it was already released. Write a hypothetical doc/readme/changelog/contributing section for this new enhancement, code snippets and all.
  validations:
    required: true
- type: textarea
  id: use-cases
  attributes:
    label: Use Cases
    placeholder: |
      What problems does this solves? List of use cases this feature or enhancement is designed to address.
  validations:
    required: true
- type: textarea
  id: implementation-notes
  attributes:
    label: Implementation Notes
    description: 
    placeholder: |
      Any thoughts regarding how this should be implemented?
- type: dropdown
  id: Component
  attributes:
    label: Component
    description: "Which component(s) in the toolchain is this related to?"
    multiple: true
    options:
    - Language Design
    - Compiler
    - SDK
    - Wing Console
    - Playground
    - Tutorial
    - IDE Extension
    - CLI
    - Plugins
    - Documentation
    - Development Environment
    - Contributor Experience
    - Other
  validations:
    required: false


- type: textarea
  attributes:
    label: Community Notes
    value: |
      <!-- Please keep this note for the community -->
      * Please vote by adding a 👍 reaction to the issue to help us prioritize.
      * If you are interested to work on this issue, please leave a comment.
      * If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).
