import { Construct } from "constructs";
import * as cloud from "../cloud";
import * as core from "../core";
import { BlockPublicAccess, BucketEncryption, Bucket as S3Bucket } from "aws-cdk-lib/aws-s3";
import { BucketDeployment, Source } from "aws-cdk-lib/aws-s3-deployment";
import { CaseConventions, NameOptions, ResourceNames } from "../utils/resource-names";
import { RemovalPolicy } from "aws-cdk-lib";

export const BUCKET_PREFIX_OPTS: NameOptions = {
  maxLen: 37,
  case: CaseConventions.LOWERCASE,
  disallowedRegex: /([^a-z0-9\-]+)/g,
  // add a dash to the end of the prefix to distinguish between the
  // Wing-generated portion of the name and the suffix generated by Terraform
  // suffix: "-",
};

/**
 * AWS implementation of `cloud.Bucket`.
 *
 * @inflight `@winglang/sdk.cloud.IBucketClient`
 */
export class Bucket extends cloud.BucketBase {
  private readonly bucket: S3Bucket;
  private readonly public: boolean;

  constructor(scope: Construct, id: string, props: cloud.BucketProps) {
    super(scope, id, props);

    this.public = props.public ?? false;

    const bucketPrefix = ResourceNames.generateName(this, BUCKET_PREFIX_OPTS);

    // names cannot begin with 'xn--'
    if (bucketPrefix.startsWith("xn--")) {
      throw new Error("AWS S3 bucket names cannot begin with 'xn--'.");
    }

    // names must begin with a letter or number
    if (!/^[a-z0-9]/.test(bucketPrefix)) {
      throw new Error(
        "AWS S3 bucket names must begin with a letter or number."
      );
    }


    this.bucket = new S3Bucket(this, "Default", {
      bucketName: bucketPrefix,
      encryption: BucketEncryption.S3_MANAGED,
      blockPublicAccess: this.public ? undefined : BlockPublicAccess.BLOCK_ALL,
      publicReadAccess: this.public ? true : false,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
  }

  public addObject(key: string, body: string): void {
    new BucketDeployment(this, `S3Object-${key}`, {
      destinationBucket: this.bucket,
      sources: [Source.data(key, body)],
    });
  }

  /** @internal */
  public _toInflight(): core.Code {
    return core.InflightClient.for(__filename, "BucketClient", [
      `process.env["${this.envName()}"]`,
    ]);
  }

  private envName(): string {
    return `BUCKET_NAME_${this.node.addr.slice(-8)}`;
  }
}