// This file is generated by tools/hangar/src/generate_tests.ts

import { test } from "vitest";
import { compileTest, testTest } from "../../generated_test_targets";

test("wing compile -t tf-aws", async ({ expect }) => {
  await compileTest(expect, "asynchronous_model_implicit_await_in_functions.w");
});

test("wing test", async ({ expect }) => {
  await testTest(expect, "asynchronous_model_implicit_await_in_functions.w");
});