import * as path from "path";
import * as fs from "fs";
import * as cp from "child_process";

export interface PackageOptions {
  /**
   * Directory to to save the generated package to.
   */
  readonly outdir: string;
}

export async function pack(options: PackageOptions): Promise<string> {
  // check that the library compiles to the "sim" target
  // TODO: let user specify all supported targets

  // TODO: uncomment this after https://github.com/winglang/wing/pull/4342 is merged
  // console.log('Compiling to the "sim" target...');
  // await compile(".", { target: Target.SIM });

  // check npm is installed
  try {
    cp.execSync("npm --version", { stdio: "ignore" });
  } catch {
    throw new Error(`npm is not installed. Install it from https://www.npmjs.com/get-npm`);
  }

  // check there is at least one source file
  const sourceFiles = fs.readdirSync(process.cwd()).filter((f) => f.endsWith(".w"));
  if (sourceFiles.length === 0) {
    throw new Error(`No Wing source files (.w) found in the current directory.`);
  }

  // check package.json exists
  const currentDir = process.cwd();
  const pkgJsonPath = path.join(currentDir, "package.json");
  if (!fs.existsSync(pkgJsonPath)) {
    throw new Error(`No package.json found in the current directory. Run \`npm init\` first.`);
  }

  const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"));
  pkgJson.wing = pkgJson.wing ?? true;

  // check source files will be included in the tarball
  const pkgJsonFiles = new Set(pkgJson.files ?? []);
  const expectedGlobs = ["**/*.js", "**/*.w", "!/target/**"];
  for (const glob of expectedGlobs) {
    if (!pkgJsonFiles.has(glob)) {
      pkgJsonFiles.add(glob);
    }
  }
  pkgJson.files = [...pkgJsonFiles];

  // check package.json has required fields
  const requiredFields = ["name", "version", "description", "author", "license"];
  for (const field of requiredFields) {
    if (pkgJson[field] === undefined) {
      throw new Error(`Missing required field "${field}" in package.json`);
    }
  }

  // signal that the package is a winglang library
  // (in the future "wing" may contain other options or metadata)
  pkgJson.wing = true;

  // check if "main" points to a valid file, and if not, create a dummy file
  let main = pkgJson.main ?? "index.js";
  if (!fs.existsSync(main)) {
    const lines = [];
    lines.push("// This file was generated by `wing pack`");
    lines.push(
      `console.log("${pkgJson.name} is a winglang library and cannot be used from javascript (yet). See winglang.io/docs/libraries")`
    );
    lines.push();
    fs.writeFileSync(main, lines.join("\n"));
  }
  pkgJson.main = main;

  // write package.json
  fs.writeFileSync(pkgJsonPath, JSON.stringify(pkgJson, null, 2) + "\n");

  // make tarball
  fs.mkdirSync(options.outdir, { recursive: true });
  const command = `npm pack --json --pack-destination "${options.outdir}"`;
  const output = cp.execSync(command, { stdio: "pipe" });
  const parsedOutput = JSON.parse(output.toString());
  const tarballName = parsedOutput[0].filename;
  return path.join(options.outdir, tarballName);
}
