import * as cp from "child_process";
import { constants } from "fs";
import * as fs from "fs/promises";
import * as os from "os";
import * as path from "path";
import { resolve } from "path";
import { Target } from "@winglang/compiler";
import { compile } from "./compile";
import { checkNpmVersion } from "./npm-util";

// TODO: add --dry-run option?
// TODO: print information about the generated library? (e.g. size, dependencies, number of public APIs)

export interface PackageOptions {
  /**
   * Output filename.
   */
  readonly outfile?: string;
}

export async function pack(options: PackageOptions = {}): Promise<string> {
  // check that the library compiles to the "sim" target
  // TODO: let the user specify all supported targets in package.json
  console.log('Compiling to the "sim" target...');

  // ugly hack
  // await compile(".", { target: Target.SIM });
  await compile(path.join("..", path.basename(process.cwd())), { target: Target.SIM });

  // check npm is installed
  await checkNpmVersion();

  const userDir = process.cwd();
  const outfile = options.outfile ? resolve(options.outfile) : undefined;
  const outdir = outfile ? path.dirname(outfile) : userDir;

  // perform our work in a staging directory to avoid making a mess in the user's current directory
  return withTempDir(async (workdir) => {
    const excludePaths = [
      path.join(userDir, "target"),
      path.join(userDir, "node_modules"),
      path.join(userDir, ".git"),
    ];

    // copy the user's directory to the staging directory
    await copyDir(userDir, workdir, excludePaths);

    // check package.json exists
    const pkgJsonPath = path.join(workdir, "package.json");
    if (!(await exists(pkgJsonPath))) {
      throw new Error(`No package.json found in the current directory. Run \`npm init\` first.`);
    }

    const pkgJson = JSON.parse(await fs.readFile(pkgJsonPath, "utf8"));

    // check package.json has required fields
    const requiredFields = ["name", "version", "description", "author", "license"];
    for (const field of requiredFields) {
      if (pkgJson[field] === undefined) {
        throw new Error(`Missing required field "${field}" in package.json.`);
      }
    }

    // check that Wing source files will be included in the tarball
    const pkgJsonFiles = new Set(pkgJson.files ?? []);
    const expectedGlobs = ["**/*.js", "**/*.w"];
    for (const glob of expectedGlobs) {
      if (!pkgJsonFiles.has(glob)) {
        pkgJsonFiles.add(glob);
      }
    }
    pkgJson.files = [...pkgJsonFiles];

    // check if "main" points to a valid file, and if not, create a dummy file
    let main = pkgJson.main ?? "index.js";
    if (!(await exists(main))) {
      const lines = [];
      lines.push("// This file was generated by `wing pack`");
      lines.push(
        `console.log("${pkgJson.name} is a winglang library and cannot be used from javascript (yet). See winglang.io/docs/libraries")`
      );
      lines.push();
      await fs.writeFile(main, lines.join("\n"));
    }
    pkgJson.main = main;

    // add "winglang" to "keywords"
    const keywords = new Set(pkgJson.keywords ?? []);
    keywords.add("winglang");
    pkgJson.keywords = [...keywords];

    // add "wing" to "engines"
    pkgJson.engines = { wing: "*" };

    // add "wing" top-level field
    pkgJson.wing = true;

    // write package.json
    await fs.writeFile(pkgJsonPath, JSON.stringify(pkgJson, null, 2) + "\n");

    // make the tarball
    const command = `npm pack --json --pack-destination "${outdir}"`;
    const output = cp.execSync(command, { stdio: "pipe" });
    const parsedOutput = JSON.parse(output.toString());
    const tarballName = parsedOutput[0].filename;
    if (outfile) {
      await fs.rename(tarballName, path.basename(outfile));
      console.log("Created tarball:", outfile);
      return path.join(outdir, outfile);
    } else {
      console.log("Created tarball:", tarballName);
      return path.join(outdir, tarballName);
    }
  });
}

async function copyDir(src: string, dest: string, excludePaths: string[]) {
  if (excludePaths.includes(src)) {
    return;
  }

  await fs.mkdir(dest, { recursive: true });
  let entries = await fs.readdir(src, { withFileTypes: true });

  for (let entry of entries) {
    let srcPath = path.join(src, entry.name);
    let destPath = path.join(dest, entry.name);

    entry.isDirectory()
      ? await copyDir(srcPath, destPath, excludePaths)
      : await fs.copyFile(srcPath, destPath);
  }
}

/**
 * Run some work in a temporary directory.
 */
async function withTempDir<T>(work: (workdir: string) => Promise<T>): Promise<T> {
  const workdir = await fs.mkdtemp(path.join(os.tmpdir(), "wing-pack-"));
  const cwd = process.cwd();
  try {
    process.chdir(workdir);
    // wait for the work to be completed before
    // we cleanup the work environment.
    return await work(workdir);
  } finally {
    process.chdir(cwd);
    await fs.rm(workdir, { recursive: true });
  }
}

/**
 * Check if a file exists for an specific path
 */
export async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(
      filePath,
      constants.F_OK | constants.R_OK | constants.W_OK //eslint-disable-line no-bitwise
    );
    return true;
  } catch (er) {
    return false;
  }
}
