primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
