/// This file is generated by Wing.
export interface Lifts {
};
type HandlerFunction<T> = T extends { handle: (...args: any[]) => any } ? T['handle'] : T;
type ExpectedFunction = HandlerFunction<(arg0: string) => Promise<string>>;
export type Handler = (ctx: Lifts, ...args: Parameters<ExpectedFunction>) => ReturnType<ExpectedFunction>;
export function inflight(handler: Handler): Handler { return handler; }
export default inflight;
