import child_process from "child_process";
import { readFileSync, unlinkSync } from "fs";
import { resolve } from "path";
import {
  test,
  expect,
  afterAll,
  vi,
  describe,
  SpyInstance,
  afterEach,
} from "vitest";
import * as ex from "../../src/ex";
import { ApiAttributes } from "../../src/target-sim/schema-resources";
import { Simulator } from "../../src/testing";
import { SimApp } from "../sim-app";

function getWebsiteUrl(s: Simulator, path: string): string {
  const apiAttrs = s.getResourceConfig(path).attrs as ApiAttributes;
  return apiAttrs.url;
}

function expectFirstArgToBe(fn: SpyInstance, firstArg: any) {
  const lastCall = fn.mock.lastCall;
  if (!lastCall) {
    throw new Error("function wasn't called");
  }
  expect(lastCall[0]).toBe(firstArg);
}

describe("Testing ReactWebsite", () => {
  const execMock = vi.spyOn(child_process, "exec");

  afterAll(() => {
    execMock.mockReset();
  });

  afterEach(() => {
    unlinkSync(
      resolve(__dirname, "../test-files/react-website/public/wing.js")
    );
  });

  test("website builds and serves static files", async () => {
    // GIVEN
    const app = new SimApp();
    ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
    });

    // WHEN
    const s = await app.startSimulator();
    const websiteUrl = getWebsiteUrl(s, "/website");

    const indexPage = await fetch(websiteUrl);

    // THEN
    await s.stop();
    expect(await indexPage.text()).toEqual(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/build/index.html"),
        {
          encoding: "utf-8",
        }
      )
    );
    expect(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/public/wing.js"),
        {
          encoding: "utf-8",
        }
      )
    ).toEqual(`// This file is generated by wing
window.wingEnv = {};`);

    expectFirstArgToBe(execMock, "npm run build");
  });

  test("adding an env var to the website ", async () => {
    // GIVEN
    const app = new SimApp();
    const website = ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
    });

    website.addEnvironment("key", "value");

    // WHEN
    const s = await app.startSimulator();
    const websiteUrl = getWebsiteUrl(s, "/website");

    const indexPage = await fetch(websiteUrl);

    // THEN
    await s.stop();
    expect(await indexPage.text()).toEqual(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/build/index.html"),
        {
          encoding: "utf-8",
        }
      )
    );
    expect(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/public/wing.js"),
        {
          encoding: "utf-8",
        }
      )
    ).toEqual(`// This file is generated by wing
window.wingEnv = {
  "key": "value"
};`);

    expectFirstArgToBe(execMock, "npm run build");
  });

  test("running react website on dev mode", async () => {
    // GIVEN
    const app = new SimApp();
    ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
      isDevRun: true,
    });

    // WHEN
    const s = await app.startSimulator();

    // THEN
    await s.stop();

    expectFirstArgToBe(execMock, "PORT=3001 npm run start");
  });

  test("running react website on dev mode on custom port", async () => {
    // GIVEN
    const app = new SimApp();
    ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
      isDevRun: true,
      localPort: "4032",
    });

    // WHEN
    const s = await app.startSimulator();

    // THEN
    await s.stop();

    expectFirstArgToBe(execMock, "PORT=4032 npm run start");
  });

  test("running react website on dev mode with custom command", async () => {
    // GIVEN
    const CUSTOM_COMMAND = "echo 'custom command'";
    const app = new SimApp();
    ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
      startCommand: CUSTOM_COMMAND,
      isDevRun: true,
    });

    // WHEN
    const s = await app.startSimulator();

    // THEN
    await s.stop();

    expectFirstArgToBe(execMock, `PORT=3001 ${CUSTOM_COMMAND}`);
  });

  test("running react website with custom command", async () => {
    // GIVEN
    const CUSTOM_COMMAND = "echo 'custom command'";
    const app = new SimApp();
    ex.ReactWebsite._newReactWebsite(app, "website", {
      projectPath: resolve(__dirname, "../test-files/react-website"),
      buildCommand: CUSTOM_COMMAND,
    });

    // WHEN
    const s = await app.startSimulator();
    const websiteUrl = getWebsiteUrl(s, "/website");

    const indexPage = await fetch(websiteUrl);

    // THEN
    await s.stop();
    expect(await indexPage.text()).toEqual(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/build/index.html"),
        {
          encoding: "utf-8",
        }
      )
    );
    expect(
      readFileSync(
        resolve(__dirname, "../test-files/react-website/public/wing.js"),
        {
          encoding: "utf-8",
        }
      )
    ).toEqual(`// This file is generated by wing
window.wingEnv = {};`);

    expectFirstArgToBe(execMock, CUSTOM_COMMAND);
  });
});
