import { execSync } from "child_process";
import { existsSync, unlinkSync } from "fs";
import { join } from "path";
import { Construct } from "constructs";
import { Website } from "./website";
import { core } from "..";

import * as cloud from "../cloud";
import { Connections } from "../core";
import * as ex from "../ex";

/**
 * AWS implementation of `ex.ReactApp`.
 *
 * @inflight `@winglang/sdk.cloud.IReactAppClient`
 */
export class ReactApp extends ex.ReactApp {
  constructor(scope: Construct, id: string, props: ex.ReactAppProps) {
    super(scope, id, props);
    this._createWebsiteHost(
      props.buildCommand ?? ex.DEFAULT_REACT_APP_BUILD_COMMAND
    );
  }

  private _createWebsiteHost(command: string) {
    execSync(command, {
      cwd: this._projectPath,
      maxBuffer: 10 * 1024 * 1024,
    });

    if (existsSync(join(this._buildPath, ex.WING_JS))) {
      unlinkSync(join(this._buildPath, ex.WING_JS));
    }

    this._websiteHost = cloud.Website._newWebsite(
      this,
      `${this.node.id}-host`,
      {
        ...this._hostProps,
        path: this._buildPath,
      }
    );

    this.node.addDependency(this._websiteHost);
    Connections.of(this).add({
      source: this,
      target: this._websiteHost as Website,
      name: `host`,
    });
  }

  public _preSynthesize(): void {
    const env = Object.fromEntries(this._environmentVariables.entries());
    const content = `// This file is generated by wing\nwindow.wingEnv = ${JSON.stringify(
      env,
      null,
      2
    )};`;
    (this._websiteHost as Website).addFile(
      ex.WING_JS,
      content,
      "text/javascript"
    );
  }

  /** @internal */
  public _toInflight(): string {
    return core.InflightClient.for(
      __dirname.replace("target-tf-aws", "shared-aws"),
      __filename,
      "ReactAppClient",
      []
    );
  }
}
