#!/bin/sh

scriptdir=$(cd $(dirname $0) && pwd)
reporoot=$(cd $scriptdir/.. && pwd)
cd $scriptdir

# install sdk
if [ ! -d node_modules ]; then
  npm i
fi

# build wingc
(
  cd $reporoot/wingc
  cargo build --quiet
)

#export WINGRR_ROOT=$reporoot/wingrr/build
#export LD_LIBRARY_PATH=$WINGRR_ROOT

# compile
mkdir -p target
$reporoot/wingc/target/debug/wingc $1
