name: Console Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: wing-console-pr-${{github.event.number}}

jobs:
  create:
    name: "Create"
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          if ! flyctl status --app "$APP_NAME"; then
            pushd ./apps/wing-console/console/app/preview
            flyctl launch --no-deploy --copy-config --name "$APP_NAME" --image-label latest
            popd
          fi
          flyctl deploy . --config ./apps/wing-console/console/app/preview/fly.toml --app "$APP_NAME" --image-label latest --vm-memory 512 --strategy immediate
          flyctl scale count 1 --yes --app "$APP_NAME"
  destroy:
    name: "Destroy"
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          flyctl apps destroy "$APP_NAME" -y