name: Compatibility matrix update
on:
  workflow_call: {}

env:
  NODE_VERSION: "20.11.1"
  PNPM_VERSION: "8.15.1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm Dependencies
        run: pnpm install --frozen-lockfile --filter ./tools/compatibility-matrix-automation

      - name: Download Output Files
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out

      - name: Run Update Script
        run: |
          cd tools/compatibility-matrix-automation
          TEST_OUTPUT_FOLDER=../../out npx update-matrix

      - name: Create a PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          title: "chore(docs): compatibility matrix update"
          branch: "github-actions/updating-matrix"
          base: main
          add-paths: docs/**
          commit-message: |-
            Updates the [Compatibility Matrix](https://www.winglang.io/docs/standard-library/compatibility-matrix)

            [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ------

            *Automatically created via the "matrix-update" workflow*
          body: |-
            chore(docs): update compatibility matrix

            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ------

            *Automatically created via the "matrix-update" workflow*
          author: monabot <monabot@monada.co>
          committer: monabot <monabot@monada.co>
          signoff: true
          labels: 📚 documentation
          delete-branch: true
