name: "PR Build"

on:
  push:
  pull_request:

env:
  CI: true
  NODEJS_VERSION: "18.x"
  MONADAHQ_REGISTRY: "https://npm.pkg.github.com"
  # TODO Real versioning needed
  WING_VERSION: "0.1.1-dev.${{ github.run_id }}.${{ github.run_attempt }}"

jobs:
  wasm:
    name: "Non-Native Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          registry-url: https://npm.pkg.github.com

      - name: Login to Private NPM registry
        run: npm config set @monadahq:registry https://npm.pkg.github.com && npm set //npm.pkg.github.com/:_authToken ${{ secrets.PROJEN_GITHUB_TOKEN }}

      - uses: bahmutov/npm-install@v1

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup WASI Support
        run: scripts/setup_wasi.sh

      - name: Lint Nx
        run: npx nx workspace-lint

      # - name: Derive appropriate SHAs for base and head for `nx affected` commands
      #   uses: nrwl/nx-set-shas@v3

      - name: Build
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: "build"
          projects: "wing,wingsdk,wing-api-checker,wing-playground"
          args: "--configuration=release"

      - name: Test
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: "test"
          projects: "wingsdk,wing-api-checker"
          all: true
