name: "Regression Tests"
on:
  workflow_dispatch: {}
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'

jobs:
  e2e:
    name: "E2E Testing"
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node: [18, 19]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        run: |
          CURRENT_VERSION="$(git describe --tags --abbrev=0 | cut -c 2-)"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
          working-directory: |
            tools/hangar
            examples/tests/valid
            examples/tests/invalid

      - name: Run E2E Tests
        env:
          HANGAR_WING_SPEC: "${{ steps.latest-tag.outputs.version }}"
          HANGAR_WINGSDK_SPEC: "${{ steps.latest-tag.outputs.version }}"
        working-directory: tools/hangar
        run: npm run test
      