name: Release docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "logo/**"
      - "*.md"
  workflow_dispatch: {}
      
concurrency:
  group: ${{ github.workflow }}-${{ github.event.after || github.ref }}
  cancel-in-progress: true

jobs:
  release_docs:
    name: Get the latest version artifacts and release new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: scripts/docs/

      - name: Generate changelong
        id: changelog
        env:
          GENERATE_VERSION: false
        run: |
          cp scripts/changelog.mjs scripts/docs/changelog.mjs
          cd scripts/docs/
          npm run changelog

      - name: Download assets
        run: npx tsx scripts/docs/downloadAssets.ts
        env:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}

      - name: Compress docs
        run: tar -czvf docs.tgz docs/*

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        if: ${{ fromJson(steps.changelog.outputs.data).newVersion != fromJson(steps.changelog.outputs.data).lastVersion }}
        with:
          repo-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          tag: "v${{ fromJson(steps.changelog.outputs.data).newVersion }}"
      
      - name: Write changelog
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: "CHANGELOG.md"
          contents: ${{ fromJson(steps.changelog.outputs.data).changelog }}
          write-mode: overwrite

      - name: Compute checksums
        run: |
          mv docs.tgz dist/
          cd dist

          echo '' >> ../CHANGELOG.md
          echo '### SHA-1 Checksums' >> ../CHANGELOG.md
          echo '```' >> ../CHANGELOG.md
          sha1sum --binary * >> ../CHANGELOG.md
          echo '```' >> ../CHANGELOG.md
          cat ../CHANGELOG.md
      
      - name: Cut development release
        uses: softprops/action-gh-release@v1
        with:
          name: "Wing ${{ fromJson(steps.changelog.outputs.data).newVersion }}"
          tag_name: "v${{ fromJson(steps.changelog.outputs.data).newVersion }}"
          body_path: CHANGELOG.md
          files: dist/*
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}