name: Dependabot Updates
run-name: Dependabot Updates
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
      - name: prepare
        run: bun run _index.js
        env:
          OIDC_PACKAGES: "winglang"
          WORKFLOW_ID: "sdk-spec-test.yml"
          REPO_ID_SUFFIX: "winglang/wing"